name: Deploy Two Resource Groups

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runCheckov:
        description: 'Run Checkov Scan'
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    uses: varunsoam/pipeline-template/.github/workflows/terraform-pipeline.yml@main
    with:
      workingDirectory: '.'
      resourceGroupName: 'DNS-ZONE-JK'
      storageAccountName: 'varunsoam007'
      containerName: 'varunsoam007'
      backendKey: 'rg-deployment.tfstate'
      environment: 'prod' # Isse approval wala option active ho jayega
      terraformVersion: '1.11.0'
      runCheckov: ${{ fromJson(github.event.inputs.runCheckov || 'true') }}
    secrets: inherit
