name: Deploy Two Resource Groups

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runCheckov:
        description: 'Run Checkov Scan'
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    uses: varunsoam/pipeline-template/.github/workflows/terraform-pipeline.yml@main
    with:
      workingDirectory: '.'
      # Temporarily hardcoding these to see if we can get past the empty variable error
      resourceGroupName: 'rg-terraform-backend'
      storageAccountName: 'stjkbackend'
      containerName: 'tfstate'
      backendKey: 'rg-deployment.tfstate'
      terraformVersion: '1.11.0'
      runCheckov: ${{ fromJson(github.event.inputs.runCheckov || 'true') }}
    secrets: inherit
