name: Deploy Two Resource Groups

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runCheckov:
        description: 'Run Checkov Scan'
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    # Pointing to the template in the new Org
    uses: varunsoam007/pipeline-template/.github/workflows/terraform-pipeline.yml@main
    with:
      workingDirectory: '.'
      # Ab ye sari details Organization Variables se ayengi
      resourceGroupName: ${{ vars.BACKEND_RG }}
      storageAccountName: ${{ vars.BACKEND_STORAGE }}
      containerName: ${{ vars.BACKEND_CONTAINER }}
      backendKey: 'rg-deployment.tfstate'
      environment: 'prod'
      pool: 'ubuntu-latest'
      terraformVersion: '1.11.0'
      runCheckov: ${{ fromJson(github.event.inputs.runCheckov || 'true') }}
    secrets: inherit
